//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowsTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DataGridViewTemplate {
            get {
                return ((int)(this["DataGridViewTemplate"]));
            }
            set {
                this["DataGridViewTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N/A")]
        public string GameHomePath {
            get {
                return ((string)(this["GameHomePath"]));
            }
            set {
                this["GameHomePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N/A")]
        public string GameVersionHome {
            get {
                return ((string)(this["GameVersionHome"]));
            }
            set {
                this["GameVersionHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GamePrBackColorSelect {
            get {
                return ((int)(this["GamePrBackColorSelect"]));
            }
            set {
                this["GamePrBackColorSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffff6e66")]
        public string PrColor1 {
            get {
                return ((string)(this["PrColor1"]));
            }
            set {
                this["PrColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffffae66")]
        public string PrColor2 {
            get {
                return ((string)(this["PrColor2"]));
            }
            set {
                this["PrColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffffc51a")]
        public string PrColor3 {
            get {
                return ((string)(this["PrColor3"]));
            }
            set {
                this["PrColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff58e600")]
        public string PrColor4 {
            get {
                return ((string)(this["PrColor4"]));
            }
            set {
                this["PrColor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff4ecc00")]
        public string PrColor5 {
            get {
                return ((string)(this["PrColor5"]));
            }
            set {
                this["PrColor5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff03e3cb")]
        public string PrColor6 {
            get {
                return ((string)(this["PrColor6"]));
            }
            set {
                this["PrColor6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffda70f5")]
        public string PrColor7 {
            get {
                return ((string)(this["PrColor7"]));
            }
            set {
                this["PrColor7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffc111ee")]
        public string PrColor8 {
            get {
                return ((string)(this["PrColor8"]));
            }
            set {
                this["PrColor8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffffae66")]
        public string WinsColor1 {
            get {
                return ((string)(this["WinsColor1"]));
            }
            set {
                this["WinsColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff03e3cb")]
        public string WinsColor2 {
            get {
                return ((string)(this["WinsColor2"]));
            }
            set {
                this["WinsColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffc111ee")]
        public string WinsColor3 {
            get {
                return ((string)(this["WinsColor3"]));
            }
            set {
                this["WinsColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff63B8FF")]
        public string PrColor0 {
            get {
                return ((string)(this["PrColor0"]));
            }
            set {
                this["PrColor0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff949e9e")]
        public string PrColorNA {
            get {
                return ((string)(this["PrColorNA"]));
            }
            set {
                this["PrColorNA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public double WinsColorValue1 {
            get {
                return ((double)(this["WinsColorValue1"]));
            }
            set {
                this["WinsColorValue1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double WinsColorValue2 {
            get {
                return ((double)(this["WinsColorValue2"]));
            }
            set {
                this["WinsColorValue2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff000000")]
        public string DataGridViewTemplateForeColor0 {
            get {
                return ((string)(this["DataGridViewTemplateForeColor0"]));
            }
            set {
                this["DataGridViewTemplateForeColor0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffFFFFFF")]
        public string DataGridViewTemplateForeColor1 {
            get {
                return ((string)(this["DataGridViewTemplateForeColor1"]));
            }
            set {
                this["DataGridViewTemplateForeColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("750")]
        public int PrValue1 {
            get {
                return ((int)(this["PrValue1"]));
            }
            set {
                this["PrValue1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1100")]
        public int PrValue2 {
            get {
                return ((int)(this["PrValue2"]));
            }
            set {
                this["PrValue2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1350")]
        public int PrValue3 {
            get {
                return ((int)(this["PrValue3"]));
            }
            set {
                this["PrValue3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1550")]
        public int PrValue4 {
            get {
                return ((int)(this["PrValue4"]));
            }
            set {
                this["PrValue4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1750")]
        public int PrValue5 {
            get {
                return ((int)(this["PrValue5"]));
            }
            set {
                this["PrValue5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2100")]
        public int PrValue6 {
            get {
                return ((int)(this["PrValue6"]));
            }
            set {
                this["PrValue6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2450")]
        public int PrValue7 {
            get {
                return ((int)(this["PrValue7"]));
            }
            set {
                this["PrValue7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long GamePvpDataLastTime {
            get {
                return ((long)(this["GamePvpDataLastTime"]));
            }
            set {
                this["GamePvpDataLastTime"] = value;
            }
        }
    }
}
